### ISSUE TITLE
When attempting to do a schema dump getting errors on functions.

### ISSUE THREAD

**Issue by distil-brewmaster** [HornsAndHooves/pg_saurus#13]
This line is throwing an error because my database has a couple records for max/min and it doesn't like that... 

https://github.com/HornsAndHooves/pg_saurus/blob/master/lib/pg_saurus/connection_adapters/postgresql_adapter/function_methods.rb#L36

Here's the error it throws...

    ActiveRecord::StatementInvalid: PG::WrongObjectType: ERROR:  "max" is an aggregate function
    : SELECT pg_get_functiondef(559673);

Here's a couple of records from the output of the preceding SQL query.

    public	max	citext	agg	559673
    public	min	citext	agg	559672

Not sure how to avoid getting this error without modifying the SQL to exclude aggregate functions

    AND p.proisagg <> true

**Comment by albertosaurus** [comment]
@distil-brewmaster Can you give me instructions to replicate this problem?

**Comment by distil-brewmaster** [comment]
I simply do a `rake db:schema:dump`.  That causes the error.

I don't know what added those functions, I suspect the `citext` extension is what added them.

It looks like this code is exporting all functions.. even the ones that are generated by the extensions.  Is that the functionality you are looking for?

**Comment by albertosaurus** [comment]
@distil-brewmaster Let me think through whether excluding aggregate functions will cause other problems. At this point I think your suggestion is the right thing to do.

**Comment by albertosaurus** [comment]
@distil-brewmaster Version 2.5.0 fixes this.
