### ISSUE TITLE
Backport to Rails 3

### ISSUE THREAD

**Issue by jodell** [HornsAndHooves/pg_saurus#14]
We may need to backport this to rails3.  Any thoughts on supporting that idea going forward?  This issue is short-lived for my concerns but may be something useful for other people who are also behind.

**Comment by albertosaurus** [comment]
https://github.com/TMXCredit/pg_power works with Rails 3. Unless you need some piece of functionality from our subsequent work, this will do the trick. Otherwise, you can probably fork that project and then backport from pg_saurus without too much work.

**Comment by jodell** [comment]
Great, thanks.  See you on the other side.
